/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as ShippingReturnsRouteImport } from './routes/shipping-returns'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ApiSquareCheckoutRouteImport } from './routes/api/square/checkout'
import { Route as ApiSquareProductsRouteImport } from './routes/api/square/products'
import { Route as ApiSquareStatusRouteImport } from './routes/api/square/status'
import { Route as ApiSquareOauthCallbackRouteImport } from './routes/api/square/oauth/callback'
import { Route as ApiSquareOauthStartRouteImport } from './routes/api/square/oauth/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingReturnsRoute = ShippingReturnsRouteImport.update({
  id: '/shipping-returns',
  path: '/shipping-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSquareCheckoutRoute = ApiSquareCheckoutRouteImport.update({
  id: '/api/square/checkout',
  path: '/api/square/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSquareProductsRoute = ApiSquareProductsRouteImport.update({
  id: '/api/square/products',
  path: '/api/square/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSquareStatusRoute = ApiSquareStatusRouteImport.update({
  id: '/api/square/status',
  path: '/api/square/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSquareOauthCallbackRoute = ApiSquareOauthCallbackRouteImport.update({
  id: '/api/square/oauth/callback',
  path: '/api/square/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSquareOauthStartRoute = ApiSquareOauthStartRouteImport.update({
  id: '/api/square/oauth/start',
  path: '/api/square/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/square/checkout': typeof ApiSquareCheckoutRoute
  '/api/square/products': typeof ApiSquareProductsRoute
  '/api/square/status': typeof ApiSquareStatusRoute
  '/api/square/oauth/callback': typeof ApiSquareOauthCallbackRoute
  '/api/square/oauth/start': typeof ApiSquareOauthStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/square/checkout': typeof ApiSquareCheckoutRoute
  '/api/square/products': typeof ApiSquareProductsRoute
  '/api/square/status': typeof ApiSquareStatusRoute
  '/api/square/oauth/callback': typeof ApiSquareOauthCallbackRoute
  '/api/square/oauth/start': typeof ApiSquareOauthStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/square/checkout': typeof ApiSquareCheckoutRoute
  '/api/square/products': typeof ApiSquareProductsRoute
  '/api/square/status': typeof ApiSquareStatusRoute
  '/api/square/oauth/callback': typeof ApiSquareOauthCallbackRoute
  '/api/square/oauth/start': typeof ApiSquareOauthStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/order-confirmed'
    | '/shipping-returns'
    | '/shop'
    | '/product/$slug'
    | '/api/square/checkout'
    | '/api/square/products'
    | '/api/square/status'
    | '/api/square/oauth/callback'
    | '/api/square/oauth/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/order-confirmed'
    | '/shipping-returns'
    | '/shop'
    | '/product/$slug'
    | '/api/square/checkout'
    | '/api/square/products'
    | '/api/square/status'
    | '/api/square/oauth/callback'
    | '/api/square/oauth/start'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/order-confirmed'
    | '/shipping-returns'
    | '/shop'
    | '/product/$slug'
    | '/api/square/checkout'
    | '/api/square/products'
    | '/api/square/status'
    | '/api/square/oauth/callback'
    | '/api/square/oauth/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  ShippingReturnsRoute: typeof ShippingReturnsRoute
  ShopRoute: typeof ShopRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiSquareCheckoutRoute: typeof ApiSquareCheckoutRoute
  ApiSquareProductsRoute: typeof ApiSquareProductsRoute
  ApiSquareStatusRoute: typeof ApiSquareStatusRoute
  ApiSquareOauthCallbackRoute: typeof ApiSquareOauthCallbackRoute
  ApiSquareOauthStartRoute: typeof ApiSquareOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-returns': {
      id: '/shipping-returns'
      path: '/shipping-returns'
      fullPath: '/shipping-returns'
      preLoaderRoute: typeof ShippingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/square/checkout': {
      id: '/api/square/checkout'
      path: '/api/square/checkout'
      fullPath: '/api/square/checkout'
      preLoaderRoute: typeof ApiSquareCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/square/products': {
      id: '/api/square/products'
      path: '/api/square/products'
      fullPath: '/api/square/products'
      preLoaderRoute: typeof ApiSquareProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/square/status': {
      id: '/api/square/status'
      path: '/api/square/status'
      fullPath: '/api/square/status'
      preLoaderRoute: typeof ApiSquareStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/square/oauth/callback': {
      id: '/api/square/oauth/callback'
      path: '/api/square/oauth/callback'
      fullPath: '/api/square/oauth/callback'
      preLoaderRoute: typeof ApiSquareOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/square/oauth/start': {
      id: '/api/square/oauth/start'
      path: '/api/square/oauth/start'
      fullPath: '/api/square/oauth/start'
      preLoaderRoute: typeof ApiSquareOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  ShippingReturnsRoute: ShippingReturnsRoute,
  ShopRoute: ShopRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiSquareCheckoutRoute: ApiSquareCheckoutRoute,
  ApiSquareProductsRoute: ApiSquareProductsRoute,
  ApiSquareStatusRoute: ApiSquareStatusRoute,
  ApiSquareOauthCallbackRoute: ApiSquareOauthCallbackRoute,
  ApiSquareOauthStartRoute: ApiSquareOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
